theme: jekyll-theme-hacker
title: Danny Willems
author:
  name: Danny Willems
description: Fighting to follow my values. Integrity is key. Reputation is key. Fighting for privacy. Being respectful is your first duty.
