theme: jekyll-theme-hacker
title: Danny Willems
author:
  name: Danny Willems
description: A mathematician fighting for privacy and security on the Internet, while dreaming about describing the Universe with equations and symbols.
plugins:
  - jekyll-feed
