theme: jekyll-theme-hacker
title: Danny Willems - Random notes
description: Random notes on FP, blockchain/DLT, cryptography, (computational) algebra, (computational) number theory, logic, type system, entrepreneuship, maybe quantum computing. In French and in English.
