# No gem theme - fully custom layouts and SCSS
title: Danny Willems
url: https://dannywillems.github.io
baseurl: ""
author:
  name: Danny Willems
description: >-
  A mathematician fighting for privacy and security on the Internet, while
  dreaming about describing the Universe with equations and symbols.
  Cryptography researcher and engineer. Founder of BaDaaS. Building Papyrus and
  cryptography.academy. Co-founder of LeakIX.
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
