theme: jekyll-theme-hacker
title: Random notes
description: Random notes on FP, blockchain/DLT, crypto currency, cryptography, (computational) algebra, (computational) number theory, logic, type system, entrepreneuship, maybe quantum computing. In French and in English.
